[WIP] vendor: Replace Godep with glide
kubernetes/heapster pull request #1335
Opened 2016-10-12 14:25 UTC by nhlfr

Fixes #1314

2016-10-14 19:19 UTC, piosz commented
Did you bump any deps? I'd expect this change to be transparent in term of added/removed files.

2016-10-14 19:45 UTC, DirectXMan12 commented
Perhaps glide isn't doing the filtering based on used vs unused files, like Godep does?  Do we need glide-vc?

2016-10-19 12:57 UTC, AlmogBaku commented
@DirectXMan12 @piosz @nhlfr as I wrote in #1314 there is no need to commit `vendor` directory at all.. that's one of the great benefits of glide.. specify semver versions for deps, and just do `glide install` and voila!

2016-10-19 13:04 UTC, nhlfr commented
That's right. I'm going to remove the `vendor` dir today.

2016-10-19 13:07 UTC, AlmogBaku requested changes
IMO, from my experience there is no need to commit `vendor` directory at all.

2016-10-19 13:07 UTC, AlmogBaku commented on Makefile
> +	glide update
should be `glide install`

2016-10-24 16:08 UTC, AlmogBaku commented
@nhlfr can you fix the PR? it looks like the tests failed

2016-10-26 09:16 UTC, AlmogBaku requested changes

2016-10-26 09:16 UTC, AlmogBaku commented on Makefile
> +	GOOS=linux GOARCH=amd64 go test --test.short -race ./... $(FLAGS)
should be
```
GOOS=linux GOARCH=amd64 go test --test.short -v -race `glide novendor` $(FLAGS)
```

This will prevent testing the vendored libs.

2016-10-26 09:16 UTC, AlmogBaku commented on Makefile
> +	which glide-vc || go get github.com/sgotti/glide-vc
why is that needed if we are not going to commit the `vendor` dir?

2016-11-09 14:27 UTC, nhlfr commented
Looks like glide is using raw hg to fetch a repo from bitbucket...

2016-11-09 23:48 UTC, AlmogBaku commented
if im not mistaken so as godep... so why usage of hg natively here doesnt work?

2016-11-14 21:15 UTC, nhlfr commented
Probably `go get` and godep don't use `hg` as an executed command - that's my assumption, I cannot imagine any other scenario.

However, I'll try to think about and propose a change to k8s infra.

2016-11-20 13:33 UTC, AlmogBaku commented
looks very strange... since im pretty sure that godep required me to install hg..
can we re-run it again? or at least just fix the integration test?

2017-01-05 13:09 UTC, AlmogBaku commented
ping @nhlfr

2017-01-11 21:28 UTC, piosz commented
@luxas

2017-01-11 21:32 UTC, luxas commented
I would **not** switch to Glide in any k8s official projects before we have done it for core (if we really want that, I'm not sure). Actually I'm in favor for committing the vendor dir into the project, because once you've downloaded the project with git, you don't have to fetch it with glide in scripts or manually.

cc @thockin for thoughts on glide

This will not at least make the next release, and I don't think there is any argument for doing so either.

2017-01-12 06:27 UTC, thockin commented
Glide still has shortcomings and is sort of in stasis until the Go
vendoring workgroup produces results.  I would not swicth yet.  Godep is
inscrutable, but we largely understand a way to use it that works.

On Wed, Jan 11, 2017 at 1:32 PM, Lucas Käldström <notifications@github.com>
wrote:

> I would *not* switch to Glide in any k8s official projects before we have
> done it for core (if we really want that, I'm not sure). Actually I'm in
> favor for committing the vendor dir into the project, because once you've
> downloaded the project with git, you don't have to fetch it with glide in
> scripts or manually.
>
> cc @thockin <https://github.com/thockin> for thoughts on glide
>
> This will not at least make the next release, and I don't think there is
> any argument for doing so either.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/heapster/pull/1335#issuecomment-272001391>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFVgVFCW_WdssasHTLfI9TzJFPEhmBGLks5rRUqAgaJpZM4KU0JG>
> .
>

2017-01-12 08:50 UTC, piosz commented
As I wrote in https://github.com/kubernetes/heapster/issues/1314#issuecomment-253418553, I think Heapster should follow Kubernetes standards. According to what @thockin we want to stay with godeps for a while. Once Kubernetes is migrated we will revisit this decision. Closing the PR in the meantime.

2017-01-12 08:50 UTC, closed without merging