Added option ignored_labels (IgnoredLabels) to ignore certain labels
kubernetes/heapster pull request #1414
Opened 2016-12-13 19:25 UTC by galexrt

This new option allows to ignore specific metrics by label.

In a project I'm currently working on we create about 100k pods a day, InfluxDB (1.1.0) has some problems with so many series.
In the project we also only need specific metrics, so the added option to ignore specific metrics, for example ignore all type=pod, reduces the load and "too many series" InfluxDB problem.

***

Please let me know if there is anything I can improve. Please note that this is my first contribution to a project written in golang.

2017-01-11 20:48 UTC, piosz commented
@k8s-bot ok to test

2017-01-30 16:56 UTC, DirectXMan12 requested changes
I do like this feature, but we need to have something that prevents us from deleting one of the metrics needed for the resource metrics API (cpu, memory), because that will have issues on the cluster if that happens (the in-memory sink is treated like any other sink here, so deleting those metrics will cause issues there).

2017-01-30 17:05 UTC, galexrt commented
@DirectXMan12 I know what you mean.
But if someone wants to ignore/filter out specific types, the person should understand that this also disables metrics. The problem in my project case is that we don't want/need metrics of any containers (as the InfluxDB "dies" after X container series metrics).

2017-01-31 19:14 UTC, DirectXMan12 commented
> But if someone wants to ignore/filter out specific types, the person should understand that this also disables metrics. The problem in my project case is that we don't want/need metrics of any containers (as the InfluxDB "dies" after X container series metrics).

At the very least, can you add in a warning message if cpu and/or memory at the container level are skipped?  Alternatively, if there's a way to turn this on for specific sinks, that would also work (but might require a bit more work).

2017-02-01 08:56 UTC, galexrt commented
For now I would go with adding a warning when someone ignores labels, but what labels in specific?
I think showing an alert for the labels below when ignored show suffice or are there others that should also show an error?
* `pod`
* `pod_container`

2017-02-06 17:16 UTC, DirectXMan12 commented
Specificially, we care about, AFAICT (cc @piosz anything I'm forgetting?)

- container cpu/usage_rate
- container memory

if those get ignored, then we'll have issues.

2017-02-10 08:57 UTC, galexrt commented
So I should just add a warning when the label `type=container` is ignored?

2017-02-13 20:08 UTC, DirectXMan12 commented
> So I should just add a warning when the label type=container is ignored?

Yeah, that'll work.

2017-02-15 14:26 UTC, galexrt commented on metrics/heapster.go
> +		glog.Warning("Resource metrics for container are ignored. Certain metrics will not be reported!")
I added a warning as wanted.

2017-02-15 16:07 UTC, galexrt commented
The last build failure doesn't seem to be related with the PR.

2017-02-15 20:18 UTC, DirectXMan12 commented
let's trying again cc @piosz @krzyzacy is this expected due to the CI work that's being done?

 @k8s-bot test this

2017-02-15 22:51 UTC, krzyzacy commented
The change I'm making only affects if using new features from go 1.7.

Seems it's pretty green here.

2017-02-20 13:26 UTC, galexrt commented
@DirectXMan12 The warning log message has been added and CI is green now.

2017-02-24 20:08 UTC, DirectXMan12 requested changes

2017-02-24 20:08 UTC, DirectXMan12 commented on metrics/manager/manager.go
> +				labelSplit := strings.Split(label, "=")
we should probably do this ahead of time, and make it a map

2017-02-24 20:08 UTC, DirectXMan12 commented on metrics/manager/manager.go
> +				labelSplit := strings.Split(label, "=")
you might even make this a processor that can be plugged in

2017-12-05 11:36 UTC, piosz commented
Closing as obsolete. Please reopen if you still want to work on this.

2017-12-05 11:36 UTC, closed without merging