add disk io metric
kubernetes/heapster pull request #1450
Opened 2017-01-09 13:04 UTC by andyxning

Address #690.

This PR will add disk io metrics to heapster.

2017-01-09 15:21 UTC, andyxning commented
@piosz @DirectXMan12 @mwielgus PTAL.

2017-01-13 08:48 UTC, piosz commented
@timstclair @vishh can one of you take a look? Does it make sense to have those metrics?

2017-01-13 20:14 UTC, vishh commented
In on-prem clusters, disk is often a contended resource. We do not provide
any isolation for disk yet. The best we can do is to expose usage metrics.
Disk IO is a common issue and exposing that metrics to users will enable
them to identify offending pods and take action. So I'd recommend adding
metrics for "space", "inodes" and "IO" for disk

On Fri, Jan 13, 2017 at 12:48 AM, Piotr Szczesniak <notifications@github.com
> wrote:

> @timstclair <https://github.com/timstclair> @vishh
> <https://github.com/vishh> can one of you take a look? Does it make sense
> to have those metrics?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/heapster/pull/1450#issuecomment-272391229>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGvIKFT_w-7tp_eSX_LeMdlS9Q7eukwQks5rRzp0gaJpZM4LePK3>
> .
>

2017-02-21 09:31 UTC, andyxning commented
@vishh 

> So I'd recommend adding metrics for "space", "inodes" and "IO" for disk

* There is already exists `filesystem/usage`, `filesystemd/limit` and `filesystem/available` for `space`. 
* As for `inodes`, it seems that `blkio` cgroup has no info about this. I have found that inodes info is available in [cAdvisor FsStats](https://github.com/google/cadvisor/blob/master/info/v1/container.go#L436-L443). Will add this in another PR. :)
* `blkio` cgroup supports setting resource Throttling/Upper limit policy for `IO`. This is what this PR does.

2017-02-22 12:07 UTC, andyxning commented
Comments addressed. Friendly ping @timstclair @vishh

2017-03-07 14:01 UTC, andyxning commented
Friendly ping again. :) @timstclair @vishh

2017-03-16 20:38 UTC, piosz commented
Removing out of 1.3

2017-07-09 17:06 UTC, dnavre commented
This PR will be very useful especially if one runs database shards in kubernetes. Please do merge it :)

2017-09-26 22:34 UTC, weikinhuang commented
Has there been any updates on this? When running a self hosted cluster with spindle disks this is very useful information to have.

2017-10-03 15:44 UTC, DirectXMan12 commented
it needs to be rebased before it can be merged.

2017-10-27 00:23 UTC, jingxu97 commented
@andyxning, will you pick up this PR again?

2017-10-27 02:11 UTC, andyxning commented
@jingxu97 Yes. We need this also. I will rebase and resolve the conflicts in next week. 

BTW, any thoughts on the implementations or suggestions.

2017-11-14 15:33 UTC, andyxning commented
@DirectXMan12 @piosz @loburm @vishh @dnavre @weikinhuang @jingxu97 This PR is ready to review. :) 

PTAL.

2017-11-23 05:34 UTC, andyxning commented
Ping @DirectXMan12 @piosz @loburm since #1879 has been merge. This PR is ready to review and should be ready to merge too. PTAL.

2017-11-30 14:32 UTC, andyxning commented
Ping @kubernetes/heapster-maintainers 

Sorry for the complain. But can someone help me to review this PR instead of just reviewing and merging Google related ones. :(

2017-11-30 19:30 UTC, tallclair commented
This only adds the metrics for the cAdvisor source, but we're moving towards the summary source instead (parsed here: https://github.com/kubernetes/heapster/blob/master/metrics/sources/summary/summary.go).

@piosz What is the future plan for the cAdvisor source? We may remove the cAdvisor stats from the Kubelet at some point in the future.

2017-12-01 19:26 UTC, DirectXMan12 requested changes
sorry for the delay.  This needs to add metrics from the summary source, since that's the reccomended source these days.

2017-12-02 03:33 UTC, andyxning commented
> sorry for the delay. This needs to add metrics from the summary source, since that's the reccomended source these days.

According to https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/stats/v1alpha1/types.go#L110-L135, the disk io related data has not been added to stats api. I prefer to add `legacy` stats api support for now. Adding summary api support is another long term plan just like network metrics #1788 .

2017-12-04 09:40 UTC, andyxning commented
Ping @DirectXMan12

2017-12-04 16:43 UTC, DirectXMan12 commented
I'd *very* much prefer not to add anything new to the legacy source, *especially* if it's not in the summary API.  Please get it added to the summary API.

2017-12-06 15:12 UTC, andyxning commented
Ping @piosz

2017-12-07 10:26 UTC, piosz commented
@andyxning apologies for the delay. I'm fine with this PR. As @DirectXMan12 wrote please have in mind that `/stats` endpoint is deprecated in Kubelet and will be removed from there at some point, especially Heapster while using it consumes much more resources.

At the same time it's not deprecated in pure Heapster to some degree - we just need to tune Heapster a bit to work with standalone cadvisor.

2017-12-07 10:26 UTC, piosz commented
/lgtm

2017-12-07 10:26 UTC, merged

2017-12-07 15:17 UTC, andyxning commented
Thanks @DirectXMan12 @piosz . 

Yes, it is quite a question when the cluster becomes more and more large. With the original cAdvisor `stats` endpoint, more and more redundant data needs to be scraped as the cluster grows. This is quite a huge overhead. 

Btw, the summary api needs to be enhanced to accomplish our basic metrics requirements. :) Will do some works on that. :)

2017-12-13 17:42 UTC, weikinhuang commented
How do I access this in `v1.5.0` within influxdb/grafana? When I try to add a new dashboard graph, that field seems to be missing:

![screen shot 2017-12-13 at 12 41 36 pm](https://user-images.githubusercontent.com/794658/33953479-15d7e51a-e003-11e7-8c09-5ce278c1fd70.png)

2017-12-14 02:26 UTC, andyxning commented
@weikinhuang 
```
disk/io_read_bytes_rate: Number of bytes read from a disk partition per second
disk/io_write_bytes_rate: Number of bytes written to a disk partition per second
```

2017-12-14 02:27 UTC, weikinhuang commented
I don't see them in the recorded metrics

2017-12-14 16:06 UTC, andyxning commented
@weikinhuang How is your configuration for `--source`?

2017-12-14 16:11 UTC, weikinhuang commented
@andyxning Here is my deployment spec for heapster (mostly from the kubernetes/addons dir)
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster-v1.5.0
  namespace: kube-system
  labels:
    k8s-app: heapster
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    version: v1.5.0
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: heapster
      version: v1.5.0
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v1.5.0
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      containers:
        - image: gcr.io/google_containers/heapster-amd64:v1.5.0
          name: heapster
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8082
              scheme: HTTP
            initialDelaySeconds: 180
            timeoutSeconds: 5
          command:
            - /heapster
            - --source=kubernetes.summary_api:''
            - --sink=influxdb:http://monitoring-influxdb:8086
        - image: gcr.io/google_containers/heapster-amd64:v1.5.0
          name: eventer
          command:
            - /eventer
            - --source=kubernetes:''
            - --sink=influxdb:http://monitoring-influxdb:8086
        - image: gcr.io/google_containers/addon-resizer:1.7
          name: heapster-nanny
          resources:
            limits:
              cpu: 50m
              memory: 90Mi
            requests:
              cpu: 50m
              memory: 90Mi
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /pod_nanny
            - --cpu=80m
            - --extra-cpu=0.5m
            - --memory=140Mi
            - --extra-memory=4Mi
            - --deployment=heapster-v1.5.0
            - --container=heapster
            - --poll-period=300000
        - image: gcr.io/google_containers/addon-resizer:1.7
          name: eventer-nanny
          resources:
            limits:
              cpu: 50m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 200Mi
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /pod_nanny
            - --cpu=100m
            - --extra-cpu=0m
            - --memory=190Mi
            - --extra-memory=500Ki
            - --deployment=heapster-v1.5.0
            - --container=eventer
            - --poll-period=300000
      serviceAccountName: heapster
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
```

2017-12-14 17:47 UTC, weikinhuang commented
Ah. It looks like I'm using the summary API. Which does not have these metrics. Is there any issue or pr I can subscribe to for disk metrics in the summary API? Thanks @andyxning

2017-12-15 00:38 UTC, andyxning commented
@weikinhuang As for now there is not pr for adding disk io metric in summary api. I am planning to add this in next week. If you can help and make a PR about this, i will be ok to review it. :)

2017-12-15 00:40 UTC, weikinhuang commented
I would love to help, but my knowledge of golang's syntax is limited.

2017-12-15 02:10 UTC, andyxning commented
@weikinhuang To that situation, i suggest to wait for another week maybe for this feature added to summary api source. I will give it a try.

2017-12-15 02:12 UTC, weikinhuang commented
No problem, thanks @andyxning!

2018-01-25 19:57 UTC, Gimi commented
@andyxning just wondering that are you still working on adding disk metrics to summary api source?

2018-01-25 20:45 UTC, Gimi commented
I use "kubernetes" source and still am not seeing any disk metrics, any idea? I'm using gcr.io/google_containers/heapster:v1.5.0 running on kubernetes 1.8.6.

2018-01-26 04:07 UTC, andyxning commented
Any logs for heapster?

2018-01-26 04:08 UTC, andyxning commented
> just wondering that are you still working on adding disk metrics to summary api source?

Yes, i will work on this. But no time recently available working on this. :( 
Maybe one week later.

2018-01-26 17:44 UTC, Gimi commented
@andyxning no error nor warning message from heapster's log.

2018-01-27 06:49 UTC, andyxning commented
@Gimi Which sink backend do you use?

2018-02-02 22:15 UTC, Gimi commented
@andyxning sorry for the late response, I use statsd.

2018-02-07 05:54 UTC, andyxning commented
@Gimi Just have thought that do you use the summary data source? The disk io is currently only available on legacy data source.

2018-02-07 06:10 UTC, andyxning commented
@Gimi I have test master branch with statsd sink and legacy data source and the disk io metrics is available like:
> node.192_168_0_1.batch.sandbox;beta_kubernetes_io/arch.disk/io_read_bytes_rate./dev/sdb:15381.686|g
node.192_168_0_1.batch.sandbox;beta_kubernetes_io/arch.disk/io_read_bytes_rate./dev/sda:-1.3200837e+09|g
node.192_168_0_1.batch.sandbox;beta_kubernetes_io/arch.disk/io_write_bytes_rate./dev/sdb:2.1783398e+06|g
node.192_168_0_1.batch.sandbox;beta_kubernetes_io/arch.disk/io_write_bytes_rate./dev/sda:-5.901337e+10|g

2018-02-07 17:52 UTC, Gimi commented
thanks @andyxning for checking. I at the beginning did use the summary api resource, but I switched back to the legacy one when I found this ticket. But still did not see any disk metrics. I'll check again and see if I missed anything. Thank you.