the resolution should be 60 seconds but not 30
kubernetes/heapster pull request #1511
Opened 2017-02-09 07:21 UTC by tianshapjq

in the source code options/options.go, we can see that "MetricResolution" is set to be 60 seconds by default. The specifications should be corrected. Please check.

2017-02-13 20:19 UTC, DirectXMan12 requested changes
Actually, the `-model_resolution` flag doesn't exist at all anymore -- it's now `-metrics_resolution`.  Can you fix that too?  Otherwise, LGTM :+1:.

2017-02-14 00:32 UTC, tianshapjq commented
@DirectXMan12 fix done :)

2017-02-14 15:57 UTC, DirectXMan12 commented
appologies, I mistyped my earlier comment -- its `metric_resolution` (metric is singular).  Otherwise, LGTM

2017-02-15 20:01 UTC, DirectXMan12 approved these changes

2017-02-15 20:01 UTC, DirectXMan12 commented
Failure looks unrelated, not sure what's going on

2017-02-15 20:02 UTC, DirectXMan12 commented
@k8s-bot ok to test

2017-02-15 20:02 UTC, DirectXMan12 commented
once this passes, please squash the commits together and then I'll merge

2017-02-16 01:20 UTC, tianshapjq commented
I have done the squash first.

2017-02-23 20:40 UTC, merged