Wavefront Sink - moved type tag to metric namespace + unit test
kubernetes/heapster pull request #1523
Opened 2017-02-14 17:30 UTC by ezeev

We made a decision to move the "type" tag into the metric name space (i.e. `pod.cpu.usage` instead of `cpu.usage type=pod` for the Wavefront output plugin.

2017-02-15 20:06 UTC, DirectXMan12 requested changes
At a brief glance this looks good, but it contains a Makefile change which *definitely* shouldn't be there.

2017-02-15 20:06 UTC, DirectXMan12 commented on Makefile
> +PREFIX?=wavefronthq
I don't think this change should be here...

2017-02-15 22:01 UTC, ezeev commented
Thanks @DirectXMan12 - This was definitely not intended. I just corrected this. Cheers.

2017-02-17 20:41 UTC, ezeev commented
Hi @DirectXMan12 ,

Is this good to go? I'd really like to get this in before the next Heapster release.

Cheers

2017-02-24 16:21 UTC, ezeev commented on Makefile
> +PREFIX?=wavefronthq
Hi @DirectXMan12 I fixed this, is this good to merge now?

2017-02-24 16:24 UTC, ezeev commented
@DirectXMan12 @piosz 

Just looking for someone to take another look at this since I took care of the change request a few days ago.

2017-02-24 20:42 UTC, DirectXMan12 approved these changes
LGTM :+1: please squash the fixup commits together, and I'll merge this.

2017-02-27 21:42 UTC, ezeev commented
@DirectXMan12 the last commit squashes the Makefile cleanups.

2017-02-28 19:20 UTC, DirectXMan12 commented
err... there are still like 7 commits in this PR that say revert or fix.  Each commit should be a single piece of mostly self-contained new functionality, so this PR should probably just have one commit.

2017-03-03 18:35 UTC, DirectXMan12 commented
Alright, I've squashed everything down for you.  Looks good now

2017-03-03 18:39 UTC, merged