add gke sink
kubernetes/heapster pull request #1538
Opened 2017-02-21 13:45 UTC by aleksandra-malinowska

Add GKE sink to export metrics directly to Stackdriver.

2017-02-22 10:33 UTC, piosz requested changes

2017-02-22 10:33 UTC, piosz commented on metrics/sinks/gke/gke.go
> +	maxTimeseriesPerRequest = 20
Also this can be shared with gcm sink

2017-02-22 10:33 UTC, piosz commented on metrics/sinks/gke/gke.go
> +var (
const

2017-02-22 10:33 UTC, piosz commented on metrics/sinks/gke/gke.go
> +	MetricKind, ValueType, Name string
Please have one field per line.

2017-02-22 10:33 UTC, piosz commented on metrics/sinks/gke/gke.go
> +func CreateGKESink(uri *url.URL) (core.DataSink, error) {
This can be shared with gcm sink

2017-02-22 10:33 UTC, piosz commented on metrics/sinks/gke/gke.go
> +func (sink *gkeSink) sendRequest(req *stackdriver.CreateTimeSeriesRequest) {
this can be shared with gcm sink

2017-02-22 10:33 UTC, piosz commented on metrics/sinks/gke/gke.go
> +		//glog.Infof("Uptime for container: %v", resourceLabels["container_name"])
remove debug code

2017-02-22 10:33 UTC, piosz commented on metrics/sinks/gke/gke.go
> +		"namespace_id":   "",
Why namespace_id is empty?

2017-02-22 10:33 UTC, piosz commented on metrics/sinks/gke/gke.go
> +func fullProjectName(name string) string {
this can be shared with gcm sink

2017-02-22 10:33 UTC, piosz commented on metrics/sinks/gke/gke.go
> +func getReq() *stackdriver.CreateTimeSeriesRequest {
this can be shared with gcm sink

2017-02-22 10:33 UTC, piosz commented on metrics/sinks/gke/gke.go
> +	case "uptime":
Please use [MetricUptime.MetricDescriptor.Name](https://github.com/kubernetes/heapster/blob/master/metrics/core/metrics.go#L157)

2017-02-22 10:33 UTC, piosz commented on metrics/sinks/gke/gke.go
> +func (sink *gkeSink) uptimePoint(timestamp time.Time, createTime time.Time, value core.MetricValue) *stackdriver.Point {
Will you have a separate method for every point? At least interval can be somehow shared.

2017-02-23 09:21 UTC, aleksandra-malinowska commented on metrics/sinks/factory.go
> +	case "gke":
Done

2017-02-23 09:21 UTC, aleksandra-malinowska commented on metrics/sinks/gke/gke.go
> +func getReq() *stackdriver.CreateTimeSeriesRequest {
To be refactored in follow-up PR

2017-02-23 09:21 UTC, aleksandra-malinowska commented on metrics/sinks/gke/gke.go
> +func fullProjectName(name string) string {
To be refactored in follow-up PR

2017-02-23 09:21 UTC, aleksandra-malinowska commented on metrics/sinks/gke/gke.go
> +func (sink *gkeSink) uptimePoint(timestamp time.Time, createTime time.Time, value core.MetricValue) *stackdriver.Point {
Will change in next PR (adding more metrics)

2017-02-23 09:21 UTC, aleksandra-malinowska commented on metrics/sinks/gke/gke.go
> +		"namespace_id":   "",
Fixed

2017-02-23 09:21 UTC, aleksandra-malinowska commented on metrics/sinks/gke/gke.go
> +		//glog.Infof("Uptime for container: %v", resourceLabels["container_name"])
Done

2017-02-23 09:21 UTC, aleksandra-malinowska commented on metrics/sinks/gke/gke.go
> +	case "uptime":
Done

2017-02-23 09:22 UTC, aleksandra-malinowska commented on metrics/sinks/gke/gke.go
> +	MetricKind, ValueType, Name string
Done

2017-02-23 09:22 UTC, aleksandra-malinowska commented on metrics/sinks/gke/gke.go
> +func CreateGKESink(uri *url.URL) (core.DataSink, error) {
To be refactored in follow-up PR

2017-02-23 09:22 UTC, aleksandra-malinowska commented on metrics/sinks/gke/gke.go
> +func (sink *gkeSink) sendRequest(req *stackdriver.CreateTimeSeriesRequest) {
To be refactored in follow-up PR

2017-02-23 09:23 UTC, aleksandra-malinowska commented on metrics/sinks/gke/gke.go
> +	maxTimeseriesPerRequest = 20
Done

2017-02-23 09:23 UTC, aleksandra-malinowska commented on metrics/sinks/gke/gke.go
> +var (
AFAIU it's impossible to declare const structs?

2017-02-23 09:46 UTC, piosz requested changes

2017-02-23 09:46 UTC, piosz commented on metrics/sinks/stackdriver/stackdriver.go
> +// Copyright 2015 Google Inc. All Rights Reserved.
2017

2017-02-23 09:46 UTC, piosz commented on metrics/sinks/stackdriver/stackdriver.go
> +			ForceSendFields: []string{"DoubleValue"},
Why do you need this?

2017-02-23 09:46 UTC, piosz commented on metrics/sinks/stackdriver/stackdriver.go
> +			Labels: map[string]string{},
Why do you need to specify empty set of labels?

2017-02-23 09:46 UTC, piosz commented on metrics/sinks/stackdriver/stackdriver.go
> +func createTimeSeries(resourceLabels map[string]string, labels map[string]string, metadata *metricMetadata, point *sd_api.Point) *sd_api.TimeSeries {
labels are not used

2017-02-23 09:46 UTC, piosz commented on metrics/sinks/stackdriver/stackdriver.go
> +	return "GKE Sink"
Stackdriver sink

2017-02-23 11:06 UTC, aleksandra-malinowska commented on metrics/sinks/stackdriver/stackdriver.go
> +			ForceSendFields: []string{"DoubleValue"},
Not adding this field caused custom metrics to be rejected by Stackdriver. I did a test and writing GKE container metrics seems to work without it, removing this (although kubelet-to-gcm still uses it?)

2017-02-23 11:06 UTC, aleksandra-malinowska commented on metrics/sinks/stackdriver/stackdriver.go
> +			Labels: map[string]string{},
Removed

2017-02-23 11:06 UTC, aleksandra-malinowska commented on metrics/sinks/stackdriver/stackdriver.go
> +func createTimeSeries(resourceLabels map[string]string, labels map[string]string, metadata *metricMetadata, point *sd_api.Point) *sd_api.TimeSeries {
Fixed

2017-02-23 11:06 UTC, aleksandra-malinowska commented on metrics/sinks/stackdriver/stackdriver.go
> +	return "GKE Sink"
Fixed

2017-02-23 11:06 UTC, aleksandra-malinowska commented on metrics/sinks/stackdriver/stackdriver.go
> +// Copyright 2015 Google Inc. All Rights Reserved.
Fixed

2017-02-23 11:20 UTC, aleksandra-malinowska commented on metrics/sinks/stackdriver/stackdriver.go
> +// Copyright 2015 Google Inc. All Rights Reserved.
This causes 'make sanitize' to fail, so keeping 2015

2017-02-23 20:21 UTC, piosz approved these changes
LGTM, thanks for the PR!

2017-02-23 20:21 UTC, piosz commented on metrics/sinks/stackdriver/stackdriver.go
> +// Copyright 2015 Google Inc. All Rights Reserved.
ACK

2017-02-23 20:21 UTC, merged

2017-02-23 20:42 UTC, DirectXMan12 commented
You'll need to also update the sink owners file.