add more metrics to Stackdriver sink
kubernetes/heapster pull request #1550
Opened 2017-02-24 13:43 UTC by aleksandra-malinowska

Adding more metrics to send directly to Stackdriver.

2017-02-24 20:41 UTC, DirectXMan12 requested changes
Please update the sink-owners document to add the stackdriver sink.  We should not have any sinks that are not listed in that document.

2017-03-01 10:59 UTC, aleksandra-malinowska commented
Updated sink-owners document.

2017-03-02 19:18 UTC, DirectXMan12 requested changes
minor nit on the sink-owners doc, afterwards I have no objections to this.

2017-03-02 19:18 UTC, DirectXMan12 commented on docs/sink-owners.md
> +| Stackdriver     | :heavy_check_mark: | :x:                | @kubernetes/heapster-maintainers              | :new: #1538    |
:new: means it's in development/not-yet-merged this should probably just be :ok:

2017-03-02 19:23 UTC, aleksandra-malinowska commented on docs/sink-owners.md
> +| Stackdriver     | :heavy_check_mark: | :x:                | @kubernetes/heapster-maintainers              | :new: #1538    |
fixed

2017-03-02 20:47 UTC, aleksandra-malinowska commented
@k8s-bot test this

2017-03-09 21:08 UTC, DirectXMan12 approved these changes

2017-03-09 21:08 UTC, merged