Validate metric resolution
kubernetes/heapster pull request #1571
Opened 2017-03-16 11:40 UTC by bruceauyeung

this PR fixes a bug when metric_resolution is less than DefaultScrapeOffset. When metric_resolution is less than DefaultScrapeOffset, some MetricSets will not be scraped from sources

in `Housekeep()` function ( `manager.go` ) , let's assume:
1. we ignore execution time of one iteration of `Housekeep()` function
2. metric_resolution: `4s`
3. now time in first iteration:  `13:03` ( format  minutes : seconds)

then in first iteration:
start : `13:00`
end: `13:04`

and then the second iteration:
now: `13:09`
start: `13:08`
end: `13:12`

we can see MetricSets between 13:04 and 13:08 will not be scraped.

if metric_resolution is equal to or greater than scrapeOffset, this case will not happen.

2017-03-16 21:38 UTC, piosz commented
@k8s-bot ok to test

2017-03-20 23:10 UTC, DirectXMan12 commented
Just FYI, metric resolution really shouldn't be lower than 30s anyway, because of issues with cAdvisor.

2017-03-21 00:44 UTC, bruceauyeung commented
@DirectXMan12 would you please give a link about the bug of cAdvisor ? i'd like to know why. thanks!

2017-03-21 08:10 UTC, bruceauyeung commented
@DirectXMan12 fixed as you sugguested

2017-03-21 09:36 UTC, bruceauyeung commented
@DirectXMan12 fixed test case error

2017-03-21 20:47 UTC, DirectXMan12 commented on metrics/manager/manager_test.go
> +	time.Sleep(time.Millisecond * 4500 * 30)
I'm not entirely certain what the intention here is of multiplying by 30.  Please, let's not have magic numbers (at least not without better comments).

2017-03-21 20:48 UTC, DirectXMan12 requested changes
small change, but otherwise looks good

2017-03-22 04:55 UTC, bruceauyeung commented on metrics/manager/manager_test.go
> +	time.Sleep(time.Millisecond * 4500 * 30)
@DirectXMan12 already done, and the test case error gone.

2017-03-28 01:17 UTC, bruceauyeung commented
@DirectXMan12 i already have fixed as you requested, would you mind take an another look ?

2017-03-28 16:35 UTC, DirectXMan12 requested changes

2017-03-28 16:35 UTC, DirectXMan12 commented on metrics/manager/manager_test.go
> +	// 4.5 * MinMetricResolution, about 4-5 cycles
now that I think about it, I don't see much reason to actually respect the minimum metric resolution with the dummy sink -- this is just going to make the tests take *way* longer to run.

2017-03-28 16:35 UTC, DirectXMan12 commented on metrics/manager/manager_test.go
> +	// 4.5 * MinMetricResolution, about 4-5 cycles
(so, I don't think there's much reason to change the tests here)

2017-06-02 14:54 UTC, andyxning commented
@DirectXMan12 
> metric resolution really shouldn't be lower than 30s anyway, because of issues with cAdvisor.

Could you please point out the what issues prevent metric resolution from being set lower than 30s.

2017-06-02 15:43 UTC, DirectXMan12 commented
@andyxning it's been a few months since I went through that code, but IIRC, most of the important bits are here: https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/google/cadvisor/manager/container.go#L359.

Kubelet sets the default housekeeping "interval" as 10 seconds, sets the max dynamic housekeeping interval as 15 seconds (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cadvisor/cadvisor_linux.go#L54), and enables dynamic housekeeping.

The duration between housekeeping intervals can be, even without dynamic housekeeping, up to 2 times the default housekeeping interval (that's what `jitter` does), meaning even if we turned off dynamic housekeeping, we get an interval that's actually anywhere between 10s and 20s.

With dynamic housekeeping, we can increase the housekeeping interval from 10s to 15s.  This is applied *before* the jitter, so theoretically, we can get an actual time between housekeepings of up to 30s.

2017-12-07 07:03 UTC, piosz commented
Closing, as it's inactive for 6+ months. Please reopen if you still want to work on this.

2017-12-07 07:03 UTC, closed without merging