Add Prometheus metrics of Stackdriver sink performance
kubernetes/heapster pull request #1575
Opened 2017-03-17 16:37 UTC by aleksandra-malinowska

Metrics for monitoring Stackdriver sink performances: requests and timeseries sent count by result.

2017-03-20 10:34 UTC, aleksandra-malinowska commented
@k8s-bot test this

2017-03-20 13:04 UTC, aleksandra-malinowska commented
cc @crassirostris

2017-03-20 13:36 UTC, crassirostris requested changes
Do you have unit tests somewhere? If so, it would be great to test this

Code SGTM

2017-03-20 13:36 UTC, crassirostris commented on metrics/sinks/stackdriver/stackdriver.go
> +	// metrics metadata
`Known metrics metadata` to be consistent with the capital letter + explain what metrics we're talking about

2017-03-20 13:36 UTC, crassirostris commented on metrics/sinks/stackdriver/stackdriver.go
> +	// prometheus metrics of sink performance
I would suggest rephrasing to `Sink metrics` or `Sink performance metrics`

2017-03-20 13:36 UTC, crassirostris commented on metrics/sinks/stackdriver/stackdriver.go
> +	// Register Prometheus metrics
`Register sink metrics` or `Register sink performance metrics` explain it better

2017-03-20 17:45 UTC, aleksandra-malinowska commented on metrics/sinks/stackdriver/stackdriver.go
> +	// metrics metadata
Done

2017-03-20 17:45 UTC, aleksandra-malinowska commented on metrics/sinks/stackdriver/stackdriver.go
> +	// prometheus metrics of sink performance
Done

2017-03-20 17:45 UTC, aleksandra-malinowska commented on metrics/sinks/stackdriver/stackdriver.go
> +	// Register Prometheus metrics
Done

2017-03-20 17:49 UTC, crassirostris approved these changes

2017-03-22 08:17 UTC, piosz commented
LGTM

2017-03-22 08:17 UTC, merged