add OpenTSDB to storage backends list
kubernetes/heapster pull request #1576
Opened 2017-03-17 17:43 UTC by jakon89

2017-03-20 23:06 UTC, DirectXMan12 commented
Why don't we just change this list to point to the `sink-owners.md` file or something of the sort?

2017-03-20 23:06 UTC, DirectXMan12 requested changes
Why don't we just change this entire paragraph to point to the `sink-owners.md` doc (or something similar) instead?

2017-03-25 09:50 UTC, jakon89 commented
@DirectXMan12 
not sure what you meant but PTAL. Thanks

2017-03-27 15:48 UTC, DirectXMan12 requested changes
one small nit, otherwise LGTM :+1:

2017-03-27 15:48 UTC, DirectXMan12 commented on README.md
> +Heapster supports a pluggable storage backends described [here](docs/sink-owners.md).
`Heapster supports the pluggable...` (s/ a / the /).

2017-03-27 18:11 UTC, jakon89 commented
Updated. Thanks!

2017-03-28 17:41 UTC, DirectXMan12 approved these changes

2017-03-28 17:41 UTC, DirectXMan12 commented
I'd like to get an ok from @piosz as well (since this is a "front page" change, so to speak), but it looks good to me.

2017-06-21 14:42 UTC, piosz commented
/lgtm

2017-06-21 14:42 UTC, merged