Disable metric export flag [WIP]
kubernetes/heapster pull request #1580
Opened 2017-03-20 13:05 UTC by aleksandra-malinowska

To be rebased when #1575 is merged.

2017-03-22 08:20 UTC, piosz commented
Looks good. Please rebase.

2017-03-23 10:23 UTC, piosz requested changes

2017-03-23 10:23 UTC, piosz commented on metrics/options/options.go
> +	fs.BoolVar(&h.DisableMetricExport, "disable_export", false, "Disable exporting metrics in api/v1/")
api/v1/metric-export

2017-03-23 10:23 UTC, piosz commented on metrics/api/v1/api_test.go
>  func TestApiFactory(t *testing.T) {
Please add a simple unit test.

2017-04-04 14:41 UTC, aleksandra-malinowska commented on metrics/api/v1/api_test.go
>  func TestApiFactory(t *testing.T) {
Done

2017-04-05 10:10 UTC, piosz commented
LGTM

2017-04-05 10:10 UTC, piosz approved these changes

2017-04-05 10:10 UTC, merged