refactor-code-in-processors-to-add-more-readablity
kubernetes/heapster pull request #1726
Opened 2017-07-15 01:55 UTC by allencloud

I found it is a little bit hard to understand the related code.

So I try to refactor them to make them more readable.

Signed-off-by: allencloud <allen.sun@daocloud.io>

2017-07-20 15:02 UTC, allencloud commented
any update? ☀️

2017-07-20 18:29 UTC, DirectXMan12 requested changes
I'm generally in favor of this change (it brings the code more in line with general kubernetes coding conventions), but I found at least one logic error.  I'd like to get a second pair of eyes on this @piosz

2017-07-20 18:29 UTC, DirectXMan12 commented on metrics/processors/namespace_based_enricher.go
> +	if found {
`if !found`

2017-07-21 00:14 UTC, allencloud commented
Thanks for your review. @DirectXMan12  I have updated the PR. Actually double review or more is necessary and first we should absolutely make the logic consistent.

2017-07-21 15:18 UTC, DirectXMan12 approved these changes
I believe this LGTM, but I'd like to get a couple other eyes on it @mwielgus @piosz @crassirostris

2017-07-24 16:13 UTC, allencloud commented
Hi, @DirectXMan12 
Is it OK to attach a `ok-to-test` comment to this PR?
Since I think it will trigger another important test.  😄 ☀️

2017-07-24 19:25 UTC, DirectXMan12 commented
yep! :-)

/ok-to-test

2017-07-26 05:43 UTC, allencloud commented
Could you help to review this PR? @mwielgus @piosz @crassirostris
Thanks a lot. 😃

2017-08-02 15:51 UTC, allencloud commented
Could you help to review this PR? @mwielgus @piosz @crassirostris
And please feel free to tell me if I missed something.
Thanks a lot. 😃 🍻

2017-08-02 15:53 UTC, crassirostris commented
Sorry, I don't have enough context and capacity right now

2017-08-24 07:40 UTC, piosz commented
/lgtm

2017-08-24 07:41 UTC, piosz commented
Thanks @allencloud for your contribution!

2017-08-24 07:41 UTC, merged