Doc corrections
kubernetes/heapster pull request #1768
Opened 2017-08-12 08:53 UTC by rohitsardesai83

2017-08-13 14:07 UTC, andyxning commented
@rohitsardesai83 
Thanks for your contribution!

Please add some description in the PR message it is empty for now.

Overall looks good to me. Please resolve the cla, firstly. :)

2017-08-14 05:54 UTC, rohitsardesai83 commented
signed the cla

2017-08-15 07:01 UTC, rohitsardesai83 commented
@andyxning, please review and merge the PR.

2017-08-15 07:10 UTC, andyxning commented
@roberthbailey Could you please squash commits.

2017-08-19 06:56 UTC, rohitsardesai83 commented
@roberthbailey , @andyxning , is there anything I need to do here ?

2017-08-19 07:00 UTC, andyxning commented
Sorry for the error @. Could you please squash the commits.

2017-08-19 08:13 UTC, andyxning commented
@rohitsardesai83

2017-08-27 10:10 UTC, andyxning commented
/ok-to-test

2017-08-27 10:11 UTC, andyxning commented
Friendly Ping @rohitsardesai83 :-)

2017-08-27 15:11 UTC, andyxning commented
seems flakes.

/test pull-heapster-e2e

2017-08-30 15:15 UTC, andyxning commented
Since PR lgtm except commits not squashed. Multi commits does not impact the correctness.

/lgtm

2017-09-14 00:08 UTC, andyxning commented
@DirectXMan12 Could you please merge this PR since it lgtm.

2017-09-18 20:21 UTC, DirectXMan12 requested changes
some of these changes change things that are not incorrect, and others change phrasing to have subtly different meanings.

Others are correct.

2017-09-18 20:21 UTC, DirectXMan12 commented on docs/proposals/old-timer.md
> +Heapster itself to persist long-term metrics to the disk itself.  Instead, we can
this phrasing is not incorrect.  It's fine to say "persist things to disk".

2017-09-18 20:21 UTC, DirectXMan12 commented on docs/proposals/old-timer.md
> +all of the sinks and is not meant to be a general purpose query tool.
this comma was not incorrect, and the pause makes the sentence easier to parse, since it's easy to see the the last `and` is a clarification.

2017-09-18 20:21 UTC, DirectXMan12 commented on docs/proposals/push-metrics.md
> +Currently, Heapster supports pulling metrics from kubelet and defines an
also not incorrect.

2017-09-18 20:21 UTC, DirectXMan12 commented on docs/proposals/push-metrics.md
> +push mechanism are intended to be useful for consumption
you've changed the meaning of the sentence.  Whereas earlier the sentence implied that we intended that you only expose useful metrics for collection, the new sentence says that we intend all metrics exposed to be useful.  In the earlier sentence, the intention is that metrics have usefulness coming into Heapster, but with your change the metrics are granted inherent usefulness coming out of Heapster, having none to begin with.

2017-09-18 20:22 UTC, DirectXMan12 commented on docs/proposals/old-timer.md
> +Heapster itself to persist long-term metrics to the disk itself.  Instead, we can
plus, in the earlier case, "itself" refers to Heapster, while in the later case, itself is ambiguous.

2017-12-06 11:16 UTC, piosz commented
Closing as there is not progress for 2+ months. Please reopen if you want to continue working on this.

2017-12-06 11:16 UTC, closed without merging