fix network metric value for multiple interfaces
kubernetes/heapster pull request #1788
Opened 2017-08-28 10:59 UTC by andyxning

Fix #1058 

This PR will fix the network metric values when there are multiple interface available for a container. Currently, heapster will use the first one(index 0) interface stats as the value for network metrics. This will be wrong when there are more than one network interface available for a container.

What we should do is to summarize all the network interface values instead of only picking up only one.

/cc @DirectXMan12 @piosz @ckleban @CBR09 @xiangpengzhao

2017-08-29 03:27 UTC, xiangpengzhao commented
Besides this PR does, we may also want to collect and show the metrics of every network interfaces, right? i.e., the metrics can be shown in the array `interfaces` in the example of https://github.com/google/cadvisor/issues/1593

2017-08-29 03:48 UTC, andyxning commented
@xiangpengzhao IIUC, you mean that we should add a network interface label to network interface metrics?

It it is true, I suggest we postpone it as it will break the backward compatibility.

2017-08-29 04:55 UTC, xiangpengzhao commented
@andyxning correct. agreed  :)

2017-09-06 11:05 UTC, andyxning commented
/ping @DirectXMan12 @piosz

2017-09-07 14:16 UTC, DirectXMan12 requested changes
IIRC, GetValue only applies for the non-summary source, which is deprecated.  We should fix this in the summary source as well.

2017-09-07 23:59 UTC, andyxning commented
> GetValue only applies for the non-summary source, which is deprecated.

@DirectXMan12 you mean that none-summary source has been deprecated? or summary source is deprecated? I am sorry i am not getting it.

After a looking at the summary source response, i have not found any info corresponding to different interface values from it. summary source response only contains one [`NetworkStats`](https://github.com/kubernetes/heapster/blob/master/vendor/k8s.io/kubernetes/pkg/kubelet/api/v1alpha1/stats/types.go#L126-L141). I think we should first fix this in kubelet.

As for now, kubernetes 1.8 has been code freezed, it may not be added to 1.8. I will give it a try. But for now, we need this fix for normal kuberbnetes source. So would it ok for you to merge this PR first. :) I will open an issue for summary source to keep it tracked.

2017-09-08 02:22 UTC, andyxning commented
@DirectXMan12 After looking into [Kubernetes #22542](https://github.com/kubernetes/kubernetes/pull/22542), it turns out that heapster addon uses summary api by default.

2017-09-08 04:22 UTC, andyxning commented
@DirectXMan12 A fix PR has been fired to [Kubernetes #52144](https://github.com/kubernetes/kubernetes/pull/52144)

2017-10-06 00:16 UTC, andyxning commented
/ping @DirectXMan12 @piosz PTAL. Can this PR be merged?

2017-11-12 07:04 UTC, andyxning commented
@DirectXMan12 @piosz I have updated the PR in [kubernetes #52144](https://github.com/kubernetes/kubernetes/pull/52144). PTAL.

2017-11-17 06:21 UTC, bartebor commented
Summarizing network interfaces' stats can (will) give wrong results for given node when machine uses bonding for enhancing bandwith or link reliability.
For example our kubernetes nodes have two physical intefraces `eno1` and `eno2` bonded into `bond0`.
In that case we will double stats since `bond0` and its physical interfaces essentially share the same statistics.
I think we should have possibility to manually pick network interface(s) to summarize on given node. It probably should be done in kubelet, since interface names may vary from node to node. Heapster could use values from `/stats/summary`, but it is broken at the moment (searches for `eth0`) or `/stats/`, which is broken too (takes first interface from the list).

I am not sure if this applies also to container stats; I think there is no case in kubernetes where such complicated newtork setup is created.

2017-11-17 11:12 UTC, andyxning commented
@bartebor The network settings will be complicated to be coherent to all different possible network setup. For now, we should make the atomic data as detail as possible and let the upper application, like heapster, to query and make the decision about how to aggregate the original data.

2017-11-17 13:28 UTC, bartebor commented
@andyxning I agree that we should have and provide detailed network info. Heapster of course can make decision how to treat such data. The problem is nodes are different and cannot be treated in the same way.
That's why I suggested to have this done in kubelet, because we could set those policies locally while node provisioning and do not make clients aware of such peculiarities ;) 

Otherwise we should teach heapster to differentiate nodes somehow and apply specific algorithm in each case. Given that nodes come and go somewhat frequently this should be done in some general way (node labels?) to eliminate need of, say, heapster restart.

Discussion of the latter should happen in heapster issue of course.

2017-11-29 00:32 UTC, andyxning commented
@DirectXMan12 The PR in kubernetes to change summary api has been merged. Could you please take a look at this.

2017-11-30 12:53 UTC, andyxning commented
@kubernetes/heapster-maintainers PTAL.

2017-12-01 08:13 UTC, loburm requested changes

2017-12-01 08:13 UTC, loburm commented on metrics/core/metrics.go
> +		var rxErrors int64 = 0
what about:
rxErrors := uint64(0)

2017-12-01 08:13 UTC, loburm commented on metrics/core/metrics.go
> +			rxErrors += int64(interfaceStat.RxErrors)
let's make only one conversion below:
IntValue: int64(rxErrors)

2017-12-01 18:38 UTC, DirectXMan12 commented
Sorry it took me so long to get back to this.  Shouldn't we just make network a labeled metric now, instead of aggregating like this, since we now have per-interface stats?  People can aggregate together in their sink.

2017-12-02 03:00 UTC, andyxning commented on metrics/core/metrics.go
> +			rxErrors += int64(interfaceStat.RxErrors)
Will do.

2017-12-02 03:09 UTC, andyxning commented
> Shouldn't we just make network a labeled metric now, instead of aggregating like this, since we now have per-interface stats? People can aggregate together in their sink.

@DirectXMan12 IMO, make network a labeled metric is not a backward compatible change. I'd like to postpone making this change. For this PR i suggest we only fix the network metrics values. I agree that for a long run, we need to split the network metrics according to different interfaces. This need another PR, however.

2017-12-05 00:38 UTC, andyxning commented
Ping @DirectXMan12 @piosz

2017-12-05 18:36 UTC, piosz commented
/lgtm

2017-12-05 18:36 UTC, merged

2017-12-06 00:39 UTC, andyxning commented
Thanks @piosz @DirectXMan12