Add an option to read Host ID from node annotation if ExternalID is not available
kubernetes/heapster pull request #2057
Opened 2018-07-04 13:05 UTC by kawych

**What this PR does**

Fixes a bug where HostID is not populated starting with Kubernetes 1.11. ExternalID which was originally a source of HostID label was deprecated and is no longer set in Kubernetes 1.11. Starting with this version, host ID can be provided via node annotation.

2018-07-04 14:40 UTC, loburm requested changes
Just small question and then lgtm.

2018-07-04 15:10 UTC, kawych commented on metrics/api/v1/historical_handlers_test.go
> +		if test.outputError && !assert.Error(err, fmt.Sprintf("test %q should have yielded an error", test.test)) {
Reverted

2018-07-04 15:35 UTC, loburm approved these changes
/lgtm

2018-07-04 15:36 UTC, merged

2018-07-16 18:57 UTC, DirectXMan12 commented
If this is a bugfix, what's the actual bug here?  What was the issue being caused?

2018-07-17 09:49 UTC, kawych commented
This causes Heapster to label metrics incorrectly with empty host id. For Stackdriver sink, this causes a majority of metrics to not be exported.

2018-07-17 17:49 UTC, DirectXMan12 commented
Isn't that specific to the stackdriver sink, though?  Shouldn't we just have a workaround there?  It feels heavy-handed and hacky to add an entire new option and pull this from a completely optional label.  Kubernetes did remove that field for a reason, and I don't think it's a particularly good idea to hack it back in in the general case in Heapster.

2018-07-18 09:42 UTC, kawych commented
I don't think this is relevant to any other sink, but it could be. I would argue that this is a bug in Heapster sources, because the metric labels are set there. One of them is HostID, and the summary source assigns to it an incorrect value.

I have to agree that using a node annotation for this is hacky, the problem is that there is no environment-agnostic source of this information now. I identified this way to be least disruptive, as it's optional to annotate nodes and it doesn't change the default Heapster behavior. The Summary API source doesn't propagate information about node annotations to the sinks, therefore fixing this in Stackdriver sink would require either
1) Propagating all node annotations to sinks
2) Calling API Server again just to fill the missing annotations for the nodes

From my discussions about removing this field, it is key that it was a part of node spec, which is immutable. Therefore on a cloud providers where this value changed during the node update, it forced a node recreation. The optional annotation doesn't have the same problem.

2018-07-18 14:37 UTC, DirectXMan12 commented
Hmm... I'd argue the fix should have been to remove the HostID label, then, since Kubernetes removed the HostID field.  /me shrugs

Separately, if a change is adding a new flag, there should be discussion, or at least time for discussion.  Merging within a couple hours of the change landing on GitHub is not acceptable for Heapster-wide changes.  It's fine if you want to do that within the Stackdriver sink, but for this kind of thing, other people should have a chance to comment.

2018-07-18 15:15 UTC, kawych commented
Sorry for that, I considered it a small change with no effect on performance and transparent to anyone that doesn't depend on HostID label. I'll make sure to give more time for others to comment for any other PRs, for this one we can continue a discussion here whether to accept this fix or replace with something else.

Wrt. to removing HostID label completely, I wouldn't consider it as an option because it's already used by some (Stackdriver) sink. It does cause significant breakage for Stackdriver integration, i.e. all node metrics have now indistinguishable labels, Stackdriver API doesn't accept duplicate timeseries for the same period, so it rejects them. Because Heapster sends metrics in batches, this causes a rejection of the whole batch. Same thing for kubelet and docker-daemon metrics - they are identified by the instance.

2018-07-18 19:55 UTC, DirectXMan12 commented
> Sorry for that, I considered it a small change with no effect on performance and transparent to anyone that doesn't depend on HostID label.

No worries, I'm just more concerned about new config flags, etc.

> Wrt. to removing HostID label completely, I wouldn't consider it as an option because it's already used by some (Stackdriver) sink. It does cause significant breakage for Stackdriver integration, i.e. all node metrics have now indistinguishable labels

hmm... could we possibly choose a replacement to plumb through?  Is `NodeName` insufficiently unique there, or is there some wrinkle in stackdriver that makes that not work?

2018-07-19 09:12 UTC, kawych commented
Thanks for your suggestion. We considered that path, but turns out that Stackdriver relies on the instance_id matching the actual ID and there are several things that can break with such Heapster upgrade, as Stackdriver has other channels that export data as well and they need to match labels for metrics. Other problem is that the upgrade will cause too much alerts to fire due to not matching labels.

2018-07-19 14:49 UTC, DirectXMan12 commented
Ok, since this is already in, and that's a reasonable explanation, I think it's fine to keep it as-is.  As much as I would like an alternate path, I also don't want to cause too much of a headache for you guys.  In the future, please include that explanation in the PR as well.